name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_LOC_CHART: "False"
          LOCALE: "en-IN"
          POSITION: "top"
          MODE: "light"
          COMMIT_MESSAGE: "chore: update Waka stats"
          REPO: "ghulamyazdani/ghulamyazdani"
          BRANCH: "main"
          README_PATH: "README.md"
          SECTION: "waka-readme-stats"
          LINE_HEIGHT: "20px"
          THEME: "tokyonight"
          BACKGROUND_COLOR: "0D1117"
          TITLE_COLOR: "58A6FF"
          TEXT_COLOR: "C9D1D9"
          HIDE_BORDER: "true"
          LINK_TO_PROFILE: "true"
          SHOW_BADGES: "true"
          LANG_COUNT: "10"
          COMPACT: "true"
